main: codes.zucker.Reinforcement.Main
name: Reinforcement
version: 1.0
api-version: 1.16
commands:
  ri:
    description: Toggles viewing of reinforced blocks
    usage: /ri
    permission: Reinforced.ri
    permission-message: You don't have permission for that.