main: codes.zucker.ReinforcementRC.ReinforcementPlugin
name: ReinforcementRC
version: 1.1.2
api-version: 1.20
commands:
  rv:
    description: Toggles viewing of reinforced blocks
    usage: /rv
    permission: Reinforced.rv
    permission-message: You don't have permission for that.

  re:
    description: Toggles reinforcement mode
    usage: /re
    permission: Reinforced.re
    permission-message: You don't have permission for that.