main: codes.zucker.Reinforcement.ReinforcementPlugin
name: Reinforcement
version: 1.0
api-version: 1.19
commands:
  ri:
    description: Toggles viewing of reinforced blocks
    usage: /ri
    permission: Reinforced.ri
    permission-message: You don't have permission for that.

  re:
    description: Toggles reinforcement mode
    usage: /re
    permission: Reinforced.re
    permission-message: You don't have permission for that.